export const MESSAGE_TYPES = {
  INIT: 'INIT',
  CREATE_JOB: 'CREATE_JOB',
  CLEANUP: 'CLEANUP',
  FINISH_JOB: 'FINISH_JOB',
};

export const SUPPORTED_TAGS = {
  TPE1: 'array',
  TCOM: 'array',
  TCON: 'array',

  TLEN: 'integer',
  TDAT: 'integer',
  TYER: 'integer',

  WCOP: 'string',
  WCOM: 'string',
  WOAF: 'string',
  WOAR: 'string',
  WOAS: 'string',
  WORS: 'string',
  WPAY: 'string',
  WPUB: 'string',
  TLAN: 'string',
  TIT1: 'string',
  TIT2: 'string',
  TIT3: 'string',
  TALB: 'string',
  TPE2: 'string',
  TPE3: 'string',
  TPE4: 'string',
  TRCK: 'string',
  TPOS: 'string',
  TKEY: 'string',
  TMED: 'string',
  TPUB: 'string',
  TCOP: 'string',
  TEXT: 'string',
  TSRC: 'string',

  COMM: 'object',
  TXXX: 'object',
  USLT: 'object',
  TBPM: 'object',
  PRIV: 'object',
  APIC: 'object',
};

export const FRAME_TYPES = {
  album: 'TALB',
  bpm: 'TBPM',
  composer: 'TCOM',
  genre: 'TCON',
  copyright: 'TCOP',
  'encoding-time': 'TDEN',
  'playlist-delay': 'TDLY',
  'original-release-time': 'TDOR',
  'recording-time': 'TDRC',
  'release-time': 'TDRL',
  'tagging-time': 'TDTG',
  encoder: 'TENC',
  writer: 'TEXT',
  'file-type': 'TFLT',
  'involved-people': 'TIPL',
  'content-group': 'TIT1',
  title: 'TIT2',
  subtitle: 'TIT3',
  'initial-key': 'TKEY',
  language: 'TLAN',
  length: 'TLEN',
  credits: 'TMCL',
  'media-type': 'TMED',
  mood: 'TMOO',
  'original-album': 'TOAL',
  'original-filename': 'TOFN',
  'original-writer': 'TOLY',
  'original-artist': 'TOPE',
  owner: 'TOWN',
  artist: 'TPE1',
  band: 'TPE2',
  conductor: 'TPE3',
  remixer: 'TPE4',
  'set-part': 'TPOS',
  'produced-notice': 'TPRO',
  publisher: 'TPUB',
  track: 'TRCK',
  'radio-name': 'TRSN',
  'radio-owner': 'TRSO',
  'album-sort': 'TSOA',
  'performer-sort': 'TSOP',
  'title-sort': 'TSOT',
  isrc: 'TSRC',
  'encoder-settings': 'TSSE',
  'set-subtitle': 'TSST',
  'user-defined-text-information': 'TXXX',
  year: 'TYER',
  'url-commercial': 'WCOM',
  'url-legal': 'WCOP',
  'url-file': 'WOAF',
  'url-artist': 'WOAR',
  'url-source': 'WOAS',
  'url-radio': 'WORS',
  'url-payment': 'WPAY',
  'url-publisher': 'WPUB',
  comments: 'COMM',
  lyrics: 'USLT',
  image: 'APIC',
  'involved-people-list': 'IPLS',
  ownership: 'OWNE',
};

export const LOAD_STATUS = {
  INITIAL: 'INITIAL',
  PENDING: 'PENDING',
  OK: 'OK',
  ERROR: 'ERROR',
};
export const COLOR_MODE_KEY = 'pprmntcolormode';
